
cd /faststorage/project/dsmwpred/takiy/analysis12_biobanks_finngen/1_data/finngen_sumstats_folder/ # example using my folder

conda activate r4 # use R envirenment
R
library(data.table)
#read sumstat
sumstat = fread("/faststorage/project/dsmwpred/takiy/analysis12_biobanks_finngen/1_data/finngen_sumstats_folder/finngen_R8_ASTHMA_ALLERG.gz") # example using finngen_R8_ASTHMA_ALLERG.gz sumstat
setnames(sumstat,"#chrom","chrom")
summary(sumstat)
# some qc (remove non SNP varaints, MAF <0.01, info if available)
sumstat_qc1 = sumstat[nchar(ref)==1 & nchar(alt)==1 & (af_alt_cases>=0.01 & af_alt_cases<=0.99) & (af_alt_controls>=0.01 & af_alt_controls<=0.99),]

# hg38 to hg19
sumstat_qc1[,c("CHR_hg38","start","end","pos_hg38"):=.(paste0("chr",chrom),pos,pos,pos)]
sumstat_qc1[CHR_hg38=="chr23",CHR_hg38:="chrX"]

library(rtracklayer) # need to install rtracklayer from bioconductor repository conda install -c bioconda bioconductor-rtracklayer
path = system.file(package="liftOver", "extdata", "hg38ToHg19.over.chain")
ch = import.chain(path)
ch

sumstat_qc1_granges = makeGRangesFromDataFrame(sumstat_qc1,seqnames.field="CHR_hg38",start.field="start",end.field="end",keep.extra.columns=T)
sumstat_qc1_granges_res = data.table(as.data.frame(liftOver(sumstat_qc1_granges,ch)))
sumstat_qc1_granges_res [,pos_hg19 :=start]
sumstat_qc1_granges_res[,posid_hg19 := paste0(chrom,":",pos_hg19)]

# reformat sumstat keeping only columns of interst then saving
#rio::export(sumstat_qc1_format,"path/sumstat_qc1_format.tsv") # need install rio package conda install -c conda-forge r-rio, then first time loading rio "library(rio)" run install_formats() function as required