---
title: "Summary Statistics changing into LDAK format"
author: "zly"
date: "2023-12-18"
output: html_document
---

```{r setup, include=FALSE}
# library(GENESIS)
library(qqman)
library(tidyverse)
library(rpart)
library(randomForest)
library(MASS)
library(dplyr)
library(stringdist)
```

## Read Files
```{r}
df_ldak1 <- read_table("./ss_ldak/geno_LDAK_Trait_1_P5.summaries", col_names = TRUE)
df_other1 <- read_table("./ss_not_ldak/geno_LDAK_Trait_4_P2.summaries")
df_ldak <- df_ldak1[1:1000,]
df_other <- df_other1[1:1000,]

cols <- c(2,3,6,1,5,4)
df_other <- df_other[,cols]
```

## Similarity
```{r}

jaccard_similarity <- function(x, y) {
  intersection <- length(intersect(strsplit(x, NULL)[[1]], strsplit(y, NULL)[[1]]))
  union <- length(union(strsplit(x, NULL)[[1]], strsplit(y, NULL)[[1]]))
  return(intersection / union)
}

similarity_matrix <- matrix(0, nrow = ncol(df_ldak), ncol = ncol(df_other))

for (i in 1:ncol(df_ldak)) {
  for (j in 1:ncol(df_other)) {
    print(i,j)
    col1 <- as.character(df_ldak[, i])
    col2 <- as.character(df_other[, j])
     if (is.numeric(col1) && is.numeric(col2)) {
      # Euclidean distance for numeric columns
      similarity_matrix[i, j] <- 1 / (1 + sqrt(sum((col_i - col_j)^2)))
     } else{ # If char -> Jaccard similarity coefficient
      similarity_matrix[i, j] <- jaccard_similarity(col1, col2)
    }
  }
}

most_similar_column <- apply(similarity_matrix, 1, which.max)

#### Calculate the similarity between row at most_similar_column[2] and the left one or the right one, to see which are A1 and A2

if (most_similar_column[2] > 1) { # Considering if col(A1) == 1, that col(A1) -1 out of bound.
  # While it is not allowed if A2 is before A1, since there is no good way to detect which is ref and which is alt
  col_A <- as.character(df_other[,most_similar_column[2]])
  col_B <- as.character(df_other[,most_similar_column[2]+1])
  col_C <- as.character(df_other[,most_similar_column[2]-1])
  similarity_left <- jaccard_similarity(col_A, col_C)
  similarity_right <- jaccard_similarity(col_A, col_B)
  if (similarity_left > similarity_right) {
    most_similar_column[3] <- most_similar_column[2]
    most_similar_column[2] <- most_similar_column[2] - 1
  }
} else{
  most_similar_column[3] <- most_similar_column[2] + 1
}



print(most_similar_column)
most_similar_column <- c(most_similar_column)
# df_other_out <- df_other1[,most_similar_column]
# colnames(df_other_out) <- c("Predictor", "A1", "A2", "Direction", "Stat", "n")
# write.table(df_other_out, "./ss_out/test.summaries", col.names = TRUE)
```



# 2. By K-Means
```{r}

set.seed(123)
n <- 100
m1 <- 5 
m2 <- 7 


df1_chars <- data.frame(matrix(sample(letters, n * m1, replace = TRUE), ncol = m1))
df2_chars <- data.frame(matrix(sample(letters, n * m2, replace = TRUE), ncol = m2))


df1_nums <- data.frame(matrix(rnorm(n * m1), ncol = m1))
df2_nums <- data.frame(matrix(rnorm(n * m2), ncol = m2))


df1 <- cbind(df1_chars, df1_nums)
df2 <- cbind(df2_chars, df2_nums)


jaccard_similarity <- function(x, y) {
  intersection <- length(intersect(strsplit(as.character(x), NULL)[[1]], strsplit(as.character(y), NULL)[[1]]))
  union <- length(union(strsplit(as.character(x), NULL)[[1]], strsplit(as.character(y), NULL)[[1]]))
  return(1 - intersection / union)
}


result_list <- list()


for (col_df1 in colnames(df1)) {
  column_df1 <- df1[[col_df1]]

  temp_result_list <- list()

  for (col_df2 in colnames(df2)) {
    column_df2 <- df2[[col_df2]]

    is_numeric_df1 <- is.numeric(column_df1)
    is_numeric_df2 <- is.numeric(column_df2)

    if (is_numeric_df1 && is_numeric_df2) {
      # num -> Euc
      dist_matrix <- dist(cbind(column_df1, column_df2), method = "euclidean")
    } else {
      # char -> Jaccard
      dist_matrix <- stringdist::stringdistmatrix(column_df1, column_df2, method = "jaccard")
    }

    # K-means
    k <- 2  # 设置聚类数
    kmeans_result <- kmeans(as.matrix(dist_matrix), centers = k, iter.max = 100, nstart = 25, algorithm = "Lloyd")

    cluster_assignments <- kmeans_result$cluster
    most_similar_index <- which.min(kmeans_result$withinss[-1]) + 1


    temp_result_list[[col_df2]] <- tibble(
      Column_df1 = col_df1,
      Column_df2 = col_df2,
      Similarity = 1 - kmeans_result$withinss[most_similar_index] / sum(kmeans_result$withinss)
    )
  }

  temp_result_df <- bind_rows(temp_result_list)

  result_list[[col_df1]] <- temp_result_df
}

result_df <- bind_rows(result_list)
print(result_df)
```

