---
title: "SNP extract"
output: html_document
date: "2023-11-21"
---

```{r setup, include=FALSE}
# library(GENESIS)
# library(qqman)
library(tidyverse)
library(tidyr)
library(readr)
library(data.table)
library(stringr)
library(stringi)
```

## Reading icd10 and FinnGen R8 list
```{r}
# snps <- read_table2("R8_manifest.tsv", col_names = FALSE)
icd10 <- read_table2("./icdtraits.details")
finngen <- read_tsv("./R8_manifest.tsv")

finngen_100 <- read_tsv("./list_100_ss_phenocode.txt", col_names = FALSE)
finngen <- finngen_100
colnames(finngen) <- "phenocode"
```


## Matching
```{r}
icd10_pheno <- data.frame(icd10$Description)
colnames(icd10_pheno) <- c("phenocode")
# icd10_pheno <- separate(icd10_pheno, Description, into = paste0("word_", 1:8), sep = "_", remove = FALSE)
finngen_pheno <- data.frame(finngen$phenocode)
colnames(finngen_pheno) <- c("phenocode")
# finngen_pheno <- separate(finngen_pheno, phenocode, into = paste0("word_", 1:6), sep = "_", remove = FALSE)

finngen_pheno <- finngen_pheno %>%
  mutate_all(tolower)
icd10_pheno <- icd10_pheno %>%
  mutate_all(tolower)
finngen_pheno$Index <- 1:nrow(finngen_pheno)

finngen_pheno$phenocode <- sub(".*?_", "", finngen_pheno$phenocode) ## delete all the chrs before the first "_"
icd10_pheno$phenocode <- sub(".*?_", "", icd10_pheno$phenocode) ## delete all the chrs before the first "_"

################### to make finngen strings into one string without sep "_", and icd10 has "_"
################### So that when matching them, to see if a word in icd10 is totally matched with finngen substring

icd10_pheno$phenocode <- gsub("_", "", icd10_pheno$phenocode)
# icd10_pheno$phenocode <- gsub("_", "", icd10_pheno$phenocode)
finngen_pheno <- separate(finngen_pheno, phenocode, into = paste0("word_", 1:8), sep = "_", remove = FALSE)
finngen_pheno$Index <- 1:nrow(finngen_pheno)
icd10_pheno$Index <- 1:nrow(icd10_pheno)
```

## complete common substring?
```{r}


result <- data.frame(matrix(0, nrow = nrow(finngen_pheno), ncol = 8))
# result <- data.frame(matrix(0, nrow = 10, ncol = 8))
result$Indexicd <- 0
result$icd_name <- 0
for (i in 1:nrow(finngen_pheno)) {
    for (j in 2:9) {
      cat(i,j,"\n")
      if (is.na(finngen_pheno[i,j])) {
        next
      }
      for (k in 1:nrow(icd10_pheno)) {
      string1 <- finngen_pheno[i,j]
      string2 <- icd10_pheno$phenocode[k]
      # is_substring <- stri_detect_fixed(string2, string1)
      tmp <- ifelse(stri_detect_fixed(string2, string1), 1, 0)
      # cat("i =", i, ", j =", j, ", k =", k, "\n")
      # print(tmp)
      # print(string2)
      # print(string1)
      tmp_chr <- result[i,j-1]
      result[i,j-1] <- max(result[i,j-1], tmp)
      if (tmp_chr != result[i,j-1]) { # Meaning it's changed
        result$icd_name[i] <- finngen_100$X1[i]
      }
      if (tmp == 1)  {
        result$Indexicd[i] <- k
      }
      
      # result[,j-1] <- sapply(1:nrow(icd10_pheno), function(i) {
  # stri_detect(df$string2[i], df$string1[i])
# })
      # if (grepl(string1, string2)) {
        # print(i)
      # }
      }
      # print("jjjjjjjjjjjjj")
  }
  print(i)
}

result$Index <- 1:nrow(result)

```

## Delete any rows unmatched
```{r}
result_filtered <- result %>% filter_at(vars(1:10), any_vars(. != 0))

# write.table(result_filtered,"finngen_subset_in_icd10.txt",row.names = FALSE, col.names = FALSE, quote = FALSE)
result_filtered_index <- result_filtered[,c("Indexicd", "Index","icd_name")]
write.table(result_filtered_index,"finngen_100pheno_in_icd10.txt",row.names = FALSE, col.names = FALSE, quote = FALSE)

token <- merge(finngen_pheno, result_filtered, by = "Index", all.y = FALSE)
token <- token[,names(finngen_pheno)]

write.table(token,"finngen_100pheno_in_icd10_token.txt",row.names = FALSE, col.names = FALSE, quote = FALSE)

```


## Get the codes
And get a file containing one column of filenames

```{r}
list <- read_table("./finngen_100pheno_in_icd10.txt", col_names = FALSE)

code_number <- paste("/home/lezh/snpher/faststorage/biobank/newphens/icdphens/code", list$X1, sep = "")
code_number <- paste(code_number, ".pheno", sep = "")
write.table(code_number,"icd10_100pheno_ready_to_copy.txt",row.names = FALSE, col.names = FALSE, quote = FALSE)

write.table(list$X3,"icd10_100pheno_names.txt",row.names = FALSE, col.names = FALSE, quote = FALSE)
```

## Change the pheno list of 100 finngen into 42 icd10
```{r}
list_finngen <- read_table("./list_100_ss_phenocode.txt", col_names = FALSE)
list_icd10 <- read_table("./finngen_100pheno_in_icd10.txt", col_names = FALSE)
icd10 <- data.frame(list_icd10$X3)
colnames(icd10) <- "pheno"
colnames(list_finngen) <- "pheno"

finngen_42 <- merge(list_finngen, icd10, by = "pheno", all.y = FALSE)
order_index <- match(icd10$pheno, finngen_42$pheno)
finngen_42 <- data.frame(finngen_42[order_index,])

write.table(finngen_42,"finngen_42phenos.txt",row.names = FALSE, col.names = FALSE, quote = FALSE)
```


## Matching Longest Common Sequence
```{r}

find_longest_common_subsequence <- function(str1, str2) { ## LCS
  n <- nchar(str1)
  m <- nchar(str2)
  
  dp <- matrix(0, n + 1, m + 1)
  
  for (i in 1:n) {
    for (j in 1:m) {
      if (substring(str1, i, i) == substring(str2, j, j)) {
        dp[i + 1, j + 1] <- dp[i, j] + 1
      } else {
        dp[i + 1, j + 1] <- max(dp[i, j + 1], dp[i + 1, j])
      }
    }
  }
  
  i <- n
  j <- m
  lcs <- character(0)
  
  while (i > 0 && j > 0) {
    if (substring(str1, i, i) == substring(str2, j, j)) {
      lcs <- c(substring(str1, i, i), lcs)
      i <- i - 1
      j <- j - 1
    } else if (dp[i, j + 1] > dp[i + 1, j]) {
      i <- i - 1
    } else {
      j <- j - 1
    }
  }
  # print(paste(rev(lcs), collapse = ""))
  return(paste(rev(lcs), collapse = ""))
}

result <- data.frame(matrix(0, nrow = nrow(icd10_pheno), ncol = 2))
colnames(result) <- c("LCS", "MaxLength")
for (i in 1:nrow(icd10_pheno)) {
  for (j in 1:nrow(finngen_pheno)) {
    string1 <- icd10_pheno$phenocode[i]
    string2 <- finngen_pheno$phenocode[j]
    print(string1)
    print(string2)
    # output_string <- paste("String1 :", string1)
    # print(output_string)
    # output_string <- paste("String2 :", string2)
    # print(output_string)
    
    tmp <- find_longest_common_subsequence(string1, string2)
    if (nchar(tmp) > result$MaxLength[i]) {
      result$LCS[i] <- tmp
      result$MaxLength[i] <- nchar(tmp)
    }
  }
  print(i)
}


```

